logging:
  receivers:
    nscc-receiver:
      type: files
      include_paths:
        - /var/log/webapp/nscc-webapp.log
      record_log_file_path: true
  processors:
    nscc-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%d %H:%M:%S"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      default_pipeline:
        receivers: [nscc-receiver]
        processors: [nscc-processor, move_severity]
