name: Create GCP AMI CI

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Packer_Validation_WorkFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: setting up packer
        uses: hashicorp/setup-packer@main
      - name: Authentication for gcloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: setting up gcp
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: creating packer env file
        env:
          PACKER_ENVIRONMENT: ${{secrets.PACKER_ENVIRONMENT}}
        run: echo "$PACKER_ENVIRONMENT" > gcp-ami.pkrvars.hcl
      - name: creating zip file
        run: |
          rm -rf webapp.zip
          zip -r webapp.zip . -x ".git/*" ".github/*"
      - name: Run `packer init`
        run: "packer init ./gcp-ami.pkr.hcl"
      - name: Run `packer format`
        run: "packer fmt -var-file=gcp-ami.pkrvars.hcl ./gcp-ami.pkr.hcl"
      - name: Run `packer validate`
        run: "packer validate -var-file=gcp-ami.pkrvars.hcl ./gcp-ami.pkr.hcl"
      - name: Build Packer Image
        run: "packer build -var-file=gcp-ami.pkrvars.hcl ./gcp-ami.pkr.hcl"
      - name: Get Secre value
        run: |
          echo gcloud secrets versions access latest --secret=webapp-secret > webapp-secret.json
          cat webapp-secret.json
      - name: Create Instance Template
        run: |
           gcloud compute instance-templates create webapp-from-git-temp \
            --instance-template-region="us-east1" \
            --tags="webapp" \
            --machine-type="n2-standard-2" \
            --region="us-east1" \
            --network-interface=network="nscc",subnet="webapp" \
            --service-account="nscc-service@nscc-prod-2404.iam.gserviceaccount.com" \
            --scopes=logging-write,monitoring-read,monitoring-write,pubsub \
            --maintenance-policy="MIGRATE" \
            --image-project="nscc-prod-2404" \
            --image-family="nscc-custom-image" \
            --boot-disk-type="pd-standard"
