name: WebApp CI

on:
  pull_request:
    branches: [ main ]

jobs:
  Test_Checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: dependencies installation
        run: npm i
      - name: start server
        run: npm start
      - name: run node tests
        run: npm test
        
