name: WebApp CI

on:
  pull_request:
    branches: [ main ]

jobs:
  Test_Checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Checking
        run: npm test
        
