name: WebApp CI

on:
  pull_request:
    branches: [ main ]

jobs:
  CI_WorkFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: dependencies installation
        run: npm install
      - name: start mysql service
        run: sudo systemctl start mysql.service
      - name: create a database
        run: mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS nscc; SHOW DATABASES;'
      - name: integration testing
        env:
          DIALECT: ${{secrets.DIALECT}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          PORT: ${{secrets.PORT}}
        run: npm test

        
