name: WebApp CI

on:
  pull_request:
    branches: [ main ]

jobs:
  Packer_Validation_WorkFlow:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: setting up packer
        uses: hashicorp/setup-packer@main
      - name: Run `packer init`
        run: "packer init ./gcp-ami.pkr.hcl"
      - name: Run `packer format`
        run: "packer fmt -check ./gcp-ami.pkr.hcl"
      - name: Run `packer validate`
        run: "packer validate ./gcp-ami.pkr.hcl"
      
