name: UserModuleTesting CI

on:
  pull_request:
    branches: [ main ]

jobs:
  User_CI_WorkFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: dependencies installation
        run: npm install
      - name: start mysql service
        run: sudo systemctl start mysql.service
      - name: create a database
        run: mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS nscc;'
      - name : stop sql
        run: sudo systemctl stop mysql.service
      - name: integration testing
        env: 
          DIALECT: ${{secrets.DIALECT}}
          DB_NAME: ${{secrets.DATABASE_NAME}}
          DB_USERNAME: ${{secrets.USERNAME}}
          DB_PASSWORD: ${{secrets.PASSWORD}}
        run: npm test -t "user_testing"
